In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
train_x = pd.read_csv('train_desc_pca.csv')
test = pd.read_csv('test_desc_pca.csv')
label=pd.read_csv('train_label.csv')
submit = pd.read_csv('submission.csv')
train_y = label['Category']

In [3]:
classle = LabelEncoder()
train_y = classle.fit_transform(train_y)
train_y

array([0, 0, 0, ..., 2, 2, 2])

In [4]:
logi = LogisticRegression(C=100000, penalty ='l2', max_iter = 100000, random_state = 1)
logi.fit(train_x, train_y)

LogisticRegression(C=100000, max_iter=100000, random_state=1)

In [5]:
pred_y_train = logi.predict(train_x)
print(logi.score(train_x, train_y))
print(accuracy_score(train_y, pred_y_train))
print(confusion_matrix(train_y, pred_y_train))
pred_y = logi.predict(test)
pred_y = classle.inverse_transform(pred_y)

0.8045
0.8045
[[1756  150   94]
 [ 121 1609  270]
 [ 157  381 1462]]


In [6]:
submit['Category'] = pred_y
submit.to_csv('submission.csv', index=False)